### ISSUE TITLE
Method not found: 'UnityEngine.AssetBundle UnityEngine.AssetBundle.LoadFromMemory(Byte[])'

### ISSUE THREAD

**Issue by ThisKo0** [Hirashi3630/UrGUI#42]
![image](https://github.com/Hirashi3630/UrGUI/assets/81048421/ff07fa13-f94c-4cc6-b8e3-b89727dd6183)

[06:06:44.923] [Ko0-Bot] System.MissingMethodException: Method not found: 'UnityEngine.AssetBundle UnityEngine.AssetBundle.LoadFromMemory(Byte[])'.
   at UrGUI.GUIWindow.GUIWindow.LoadDefaultSkin()
   at UrGUI.GUIWindow.GUIWindow.Ini()
   at UrGUI.GUIWindow.GUIWindow.Begin(String windowTitle, Single startX, Single startY, Single startWidth, Single startHeight, Single margin, Single controlHeight, Single controlSpace, Boolean isEnabled, Boolean isDraggable, Boolean dynamicHeight)
   at UrGUI.GUIWindow.GUIWindow.Begin(String windowTitle, Single startWidth, Single margin, Single controlHeight, Single controlSpace, Boolean isEnabled, Boolean isDraggable, Boolean dynamicHeight)
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:44.935] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:45.037] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:45.038] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:45.152] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:45.153] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:45.263] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:45.264] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:45.331] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:45.331] [Ko0-Bot] System.TypeInitializationException: The type initializer for 'UrGUI.GUIWindow.Utils.GUIFormatting' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void UnityEngine.GUIStyle..ctor(UnityEngine.GUIStyle)'.
   at UrGUI.GUIWindow.Utils.GUIFormatting..cctor()
   --- End of inner exception stack trace ---
   at UrGUI.GUIWindow.Utils.GUIFormatting.get_StringStyle()
   at UrGUI.GUIWindow.Utils.GUIFormatting.GetContentStringSize(String text)
   at UrGUI.GUIWindow.GUIWindowControls.WLabel.Draw(Rect r)
   at UrGUI.GUIWindow.GUIWindow.Draw()
   at MelonTest.MainMelon.OnGUI()
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[06:06:59.159] [UnityExplorer] [UniverseLib] Can't cache type named DragState Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.BaseField`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.414] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.418] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.420] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.438] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.439] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.440] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.441] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.441] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.UIR.ShaderInfoStorage`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.442] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.UIR.ShaderInfoStorage`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.442] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.UIR.LinkedPool`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124
[06:07:04.443] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.UIR.LinkedPool`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in C:\Users\xande\Documents\Documents\Btd6 Mods\Mod Projects\UniverseLib-NewML\src\Reflection\ReflectionUtility.cs:line 124

**Comment by ThisKo0** [comment]
System.TypeInitializationException: The type initializer for 'MethodInfoStoreGeneric_AddComponent_Public_T_0`1' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   --- End of inner exception stack trace ---
   at UnityEngine.GameObject.AddComponent[T]()
   at UrGUI.UWindow.UWindowManager.InitializeManager()
   at UrGUI.UWindow.UWindowManager.Register(UWindow win)
   at UrGUI.UWindow.UWindow.Begin(String windowTitle, Single startX, Single startY, Single startWidth, Single startHeight, Single margin, Single controlHeight, Single controlSpace, Boolean isDrawing, Boolean isDraggable, Boolean dynamicHeight)
   at UrGUI.UWindow.UWindow.Begin(String windowTitle, Single startWidth, Single margin, Single controlHeight, Single controlSpace, Boolean isEnabled, Boolean isDraggable, Boolean dynamicHeight)
   at MelonTest.MainMelon.OnInitializeMelon()
   at MelonLoader.MelonBase.LoaderInitialized() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 440

**Comment by hexvalid** [comment]
some problem. i think game's libs are stripped.

**Comment by Hirashi3630** [comment]
Yes, they are stripped. Updating the Unity dlls and rebuilding it might fix it. I haven’t worked on the project in a while and unfortunately don’t have the time to maintain it at the moment.
If it fixes the issue feel free to create a pull request.
